### ISSUE TITLE
FIX to make the script work on Bullseye 5.12.2023

### ISSUE THREAD

**Issue by perivar** [cncjs/cncjs-pi-raspbian#35]
I could not make the script install neither the mjpeg stream or the ustreamer before I installed several packages before running the script.

SYSTEM:
```
Using Raspberry Pi OS (Legacy) Lite
Release date: December 5th 2023
System: 32-bit
Kernel version: 6.1
Debian version: 11 (bullseye)
```

The errors before doing this was for MJPEG-Streamer
```
  [✗]  Installing Build Tools & Dependencies | Error Code: 100
   └── Try to re-run this part of the script after rebooting.
  Latest Syslog Entries - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    Mar  2 12:25:33 cnc-control bash: E: Package 'libjpeg8-dev' has no installation candidate
```

and for uStreamer:
`_http_preprocess_request undefined reference to `__atomic_store_8'`

The fix was to install these packages before running the script.

```
sudo apt-get install -y build-essential git
sudo apt-get install htop iotop nmon lsof screen -y

sudo apt-get install cmake
sudo apt-get install make gcc
sudo apt-get install libevent-dev libjpeg62-turbo-dev libbsd-dev

```

**Comment by AustinSaintAubin** [comment]
Updated the [cncjs-pi-raspbian](https://github.com/cncjs/cncjs-pi-raspbian) install script.

The [Lite x64](https://downloads.raspberrypi.org/raspios_lite_arm64_latest) edition is now recommended.

Works with:
- NodeJS: v18.19.0
- NPM: v9.2.0
